sudo: required
language: cpp
compiler: gcc
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov
  - chmod +x install_oclint.sh
  - chmod +x build_funthing.sh
  - chmod +x get_code_cov.sh
  - chmod +x do_oclint.sh


  - ./install_oclint.sh

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
  - ./build_funthing.sh
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
